---
driver:
  name: vagrant
  network:
    -  ["private_network", {ip: "192.168.33.33" }]
    
  synced_folders:
    - [<%= File.join(ENV['PWD'], '..', '..')%>, '/tmp/repo-data']

provisioner:
  name: chef_zero
  encrypted_data_bag_secret_key_path: 'secrets/fakey-mcfakerton'
  data_bags_path: './data_bags'
  product_name: chefdk

platforms:
  - name: ubuntu-14.04
  driver:
  box: ubuntu/trusty64
  #- name: centos-7

suites:
  - name: default
    run_list:
      - recipe[test]
    attributes:
